version: '3.3'
services:
  redis:
    image: redis
  autosub:
    container_name: autosub
    image: themclg/autosub:latest
    hostname: autosub
    ports:
      - 8765:8765
    environment:
      - "PLEX_URL=http://127.0.0.1:32400" #Plex server URL including http(s):// and port
      - "PLEX_TOKEN=xxxxxxxxxxxxxx" #Your Plex token
      - "WEBHOOK_PORT=8765" #Port to listen for webhooks
      - "WHISPER_MODEL=medium" #tiny, base, small, medium, large
      - "WHISPER_DEVICE=cpu" #cpu or cuda for Nvidia GPU's
      - "WHISPER_COMPUTETYPE=int8" #Recommended: int8 for cpu or float16 for cuda
      - "WHISPER_CPUTHREADS=2" #Number of CPU threads to use (only applicable for cpu)
      - "DEBUG_LOGGING=False" #Set to True to enable debug logging
    volumes:
      - '/media:/media' #Volumes should be mapped to the same paths as your Plex server
    depends_on:
      - redis
    restart: unless-stopped